# Generated by Django 5.2.5 on 2025-08-23 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title. Used for SEO-friendly URLs.', unique=True)),
                ('description', models.TextField()),
                ('technologies_used', models.CharField(help_text='Comma-separated tech stack', max_length=200)),
                ('image', models.ImageField(upload_to='portfolio_images/%Y/%m/')),
                ('project_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this item on the homepage.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for SEO (max 160 characters).', max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title.', unique=True)),
                ('content', models.TextField(help_text='Main content of the blog post. Rich text support can be added later.')),
                ('excerpt', models.TextField(blank=True, help_text='A short summary for list views.')),
                ('featured_image', models.ImageField(upload_to='blog_images/%Y/%m/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags.', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(help_text='The date the post will be considered published.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for SEO (max 160 characters).', max_length=160)),
                ('read_time_minutes', models.PositiveIntegerField(blank=True, help_text='Calculated automatically on save.', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
